import { Router } from "express";
import { adminRouter } from "../modules/admin/AdminRoutes";
import { alertasRouter } from "../modules/alertas/AlertasRoutes";
import { almacenesRouter } from "../modules/almacenes/AlmacenesRoutes";
import { auditoriaRouter } from "../modules/auditoria/AuditoriaRoutes";
import { authRouter } from "../modules/auth/AuthRoutes";
import { categoriasRouter } from "../modules/categorias/CategoriasRoutes";
import { clientesRouter } from "../modules/clientes/ClientesRoutes";
import { comprasRouter } from "../modules/compras/ComprasRoutes";
import { erroresRouter } from "../modules/errores/ErroresRoutes";
import { marcasRouter } from "../modules/marcas/MarcasRoutes";
import { movimientosRouter } from "../modules/movimientos/MovimientosRoutes";
import { notificacionesRouter } from "../modules/notificaciones/NotificacionesRoutes";
import { prediccionRouter } from "../modules/prediccion/PrediccionRoutes";
import { productosRouter } from "../modules/productos/ProductosRoutes";
import { proveedoresRouter } from "../modules/proveedores/ProveedoresRoutes";
import { reportesRouter } from "../modules/reportes/ReportesRoutes";
import { solicitudesRouter } from "../modules/solicitudes/SolicitudesRoutes";
import { unidadesMedidaRouter } from "../modules/unidades-medida/UnidadesMedidaRoutes";
import { usuariosRouter } from "../modules/usuarios/UsuariosRoutes";
import { ventasRouter } from "../modules/ventas/VentasRoutes";

export const apiRouter = Router();

apiRouter.use("/auth", authRouter);
apiRouter.use("/usuarios", usuariosRouter);
apiRouter.use("/categorias", categoriasRouter);
apiRouter.use("/marcas", marcasRouter);
apiRouter.use("/unidades-medida", unidadesMedidaRouter);
apiRouter.use("/almacenes", almacenesRouter);
apiRouter.use("/clientes", clientesRouter);
apiRouter.use("/proveedores", proveedoresRouter);
apiRouter.use("/compras", comprasRouter);
apiRouter.use("/ventas", ventasRouter);
apiRouter.use("/productos", productosRouter);
apiRouter.use("/movimientos", movimientosRouter);
apiRouter.use("/alertas", alertasRouter);
apiRouter.use("/notificaciones", notificacionesRouter);
apiRouter.use("/prediccion", prediccionRouter);
apiRouter.use("/reportes", reportesRouter);
apiRouter.use("/admin", adminRouter);
apiRouter.use("/auditoria", auditoriaRouter);
apiRouter.use("/solicitudes", solicitudesRouter);
apiRouter.use("/errores", erroresRouter);
